-- Run this entire file in Supabase:
-- Project -> SQL Editor -> New query -> paste -> Run

create extension if not exists pgcrypto;

create table if not exists public.ranking_submissions (
  id bigint generated by default as identity primary key,
  submission_id uuid not null unique,
  anonymous_session_id text not null,
  ranking_mode text not null check (ranking_mode in ('overall', 'position')),
  ranking_lens text not null,
  board_size integer not null check (board_size in (10, 15, 20)),
  player_names jsonb not null,
  player_teams jsonb not null,
  player_positions jsonb not null,
  ranking_rows jsonb not null,
  roster_as_of date,
  page_version text,
  submitted_from text,
  created_at timestamptz not null default now()
);

alter table public.ranking_submissions enable row level security;

-- Visitors may submit rankings from the website.
drop policy if exists "public may insert rankings" on public.ranking_submissions;
create policy "public may insert rankings"
on public.ranking_submissions
for insert
to anon
with check (
  jsonb_array_length(player_names) = board_size
  and jsonb_array_length(player_teams) = board_size
  and jsonb_array_length(player_positions) = board_size
  and jsonb_array_length(ranking_rows) = board_size
);

-- There is deliberately no anonymous SELECT policy.
-- Visitors can submit, but they cannot download the central database.
-- You can view/export all rows while signed into the Supabase dashboard.

create index if not exists ranking_submissions_created_at_idx
  on public.ranking_submissions (created_at desc);

create index if not exists ranking_submissions_mode_lens_idx
  on public.ranking_submissions (ranking_mode, ranking_lens);
